[package]
name = "faktcheck"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = "0.16.1"
axum = "0.8.9"
dotenv = "0.15.0"
serde = "1.0.229"
sqlx = { version = "0.9.0", features = ["sqlite", "runtime-tokio"] }
tokio = { version = "1.53.1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["fs"] }
